### ISSUE TITLE
Unable to build wavefinder-driver for use with Psion Wavefinder

### ISSUE THREAD

**Issue by PartialVolume** [Opendigitalradio/dabtools#17]
I have a Psion Wavefinder which appears to be working as it appears in the output of lsusb
```
Bus 003 Device 005: ID 09cd:2001 Psion Dacom Home Networks, Ltd Psion WaveFinder DAB radio receiver
```
For reference I'm building this on KDE Neon (Ubuntu 22.04LTS)
I've build the main software without any build issues ..
```
cmake ../src
make
[  5%] Building C object CMakeFiles/dab2eti.dir/dab.c.o
[ 11%] Building C object CMakeFiles/dab2eti.dir/dab_tables.c.o
[ 17%] Building C object CMakeFiles/dab2eti.dir/depuncture.c.o
[ 23%] Building C object CMakeFiles/dab2eti.dir/fic.c.o
[ 29%] Building C object CMakeFiles/dab2eti.dir/input_sdr.c.o
[ 35%] Building C object CMakeFiles/dab2eti.dir/input_wf.c.o
[ 41%] Building C object CMakeFiles/dab2eti.dir/misc.c.o
[ 47%] Building C object CMakeFiles/dab2eti.dir/sdr_fifo.c.o
[ 52%] Building C object CMakeFiles/dab2eti.dir/sdr_sync.c.o
[ 58%] Building C object CMakeFiles/dab2eti.dir/wf_maths.c.o
[ 64%] Building C object CMakeFiles/dab2eti.dir/wf_prstables.c.o
[ 70%] Building C object CMakeFiles/dab2eti.dir/wf_sync.c.o
[ 76%] Building C object CMakeFiles/dab2eti.dir/dab2eti.c.o
/home/nick/Software/dabtools/src/dab2eti.c: In function ‘do_wf_decode’:
/home/nick/Software/dabtools/src/dab2eti.c:272:1: warning: no return statement in function returning non-void [-Wreturn-type]
  272 | }
      | ^
/home/nick/Software/dabtools/src/dab2eti.c: In function ‘eti_callback’:
/home/nick/Software/dabtools/src/dab2eti.c:134:3: warning: ignoring return value of ‘write’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  134 |   write(1, eti, 6144);
      |   ^~~~~~~~~~~~~~~~~~~
[ 82%] Building C object CMakeFiles/dab2eti.dir/viterbi.c.o
[ 88%] Linking C executable dab2eti
[ 88%] Built target dab2eti
[ 94%] Building C object CMakeFiles/eti2mpa.dir/eti2mpa.c.o
/home/nick/Software/dabtools/src/eti2mpa.c: In function ‘main’:
/home/nick/Software/dabtools/src/eti2mpa.c:72:5: warning: ignoring return value of ‘write’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   72 |     write(1,buf + 12 + 4*NST + FICF*96 + data_offset, data_length);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[100%] Linking C executable eti2mpa
[100%] Built target eti2mpa
```

But when I try to build the wavefinder-driver I get the following error **"**make[3]: *** No rule to make target 'arch/x86/entry/syscalls/syscall_32.tbl', needed by 'arch/x86/include/generated/uapi/asm/unistd_32.h'.  Stop.**
make[2]: *** [arch/x86/Makefile:248: archheaders] Error 2"**
```
make -C /lib/modules/6.5.0-45-generic/build SUBDIRS=/home/nick/Software/dabtools/wavefinder-driver modules
make[1]: Entering directory '/usr/src/linux-headers-6.5.0-45-generic'
**make[3]: *** No rule to make target 'arch/x86/entry/syscalls/syscall_32.tbl', needed by 'arch/x86/include/generated/uapi/asm/unistd_32.h'.  Stop.**
make[2]: *** [arch/x86/Makefile:248: archheaders] Error 2
make[1]: *** [Makefile:234: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.5.0-45-generic'
make: *** [Makefile:9: default] Error 2
```

Any suggestions as to how to resolve this would be welcome. Thanks.

**Comment by PartialVolume** [comment]
I solved the above problem by modifying the Makefile as follows:
```C
ifneq ($(KERNELRELEASE),)
	obj-m := wavefinder.o
else
KDIR        := /lib/modules/$(shell uname -r)/build
PWD         := $(shell pwd)
DEBUG	    := 1

default:
	$(MAKE) -I /usr/src/linux-headers-$(shell uname -r)/include/linux -C $(KDIR) M=$(PWD) modules
endif

```
Changing SUBDIRS=$(PWD) to M=$(PWD) got rid of the above error, however the compilation of the driver itself failed due to multiple issues including usb_maxpacket having changed the number of parameters in more recent kernels.

I'm guessing nobody is using the wavefinder driver on a recent kernel? As the last post  or commit was a number of years ago.

**Comment by LichP** [comment]
@PartialVolume Greetings from the one other person on the internet trying to make a Psion Wavefinder work in 2024! I've had some success fixing the driver for modern kernels (I'm running Arch 6.6.49-1-lts on my test system). I've corrected the compile errors and fixed some buffers to ensure they are allocated on the heap. The driver loads and recognises the device, and when I run `dab2eti 225648000` the device completes tuning and the LED lights up green, which is a good start. However `dab2eti` gets stuck on `Waiting for sync ...`, so that's as far I've got. If I enable some of the debugging in the driver it looks like the kernel is receiving USB data packets from the device, but the actual data appears to be just zeroes, which the driver ignores. I'm not sure if this is due to some other problem I've missed in the driver code, or if it's a problem with the actual device.

I've committed my changes to a fork on https://github.com/LichP/dabtools if you're interested in giving it a go. One pro-tip if you do is to add a udev rules file to set permissions on the `/dev/wavefinder0` device file (e.g. `/etc/udev/rules.d/90-wavefinder.rules` with contents `KERNEL=="wavefinder0", SUBSYSTEM=="usbmisc", MODE="0666"`), which avoids the need to run `dab2eti` as root.

**Comment by PartialVolume** [comment]
Well, it's nice to know there is at least two of us trying to get this to work :-) putting us in the top 0.00000000025% by world population. Pretty exclusive group.

I'll give your fork a try and see if I get the same results.

**Comment by PartialVolume** [comment]
Hi @LichP , Hope all is good with you. I just got round to building your source which seems to have built with no issues, although I'm not sure about the last couple of lines regarding unavailability of vmlinux. See below.

lsusb 
Bus 003 Device 012: ID 09cd:2001 Psion Dacom Home Networks, Ltd Psion WaveFinder DAB radio receiver

I've copied the wavefinder.fw to /lib/firmware/

But when I run
```
./dab2eti 218640000 > dump.eti
No supported devices found.
```
lsmod | grep -i wavefinder
Shows no wavefinder module in use

I'm not sure what to try next.

```
cmake ./src
CMake Deprecation Warning at CMakeLists.txt:5 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 13.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type not specified: defaulting to release.
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.1")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Checking for module 'librtlsdr'
--   Found librtlsdr, version 2.0.1
-- Checking for module 'fftw3'
--   Found fftw3, version 3.3.10
-- Configuring done (0.3s)
-- Generating done (0.0s)
-- Build files have been written to: /home/nick/Software/dabtools/dabtools

nick:$ ls
cmake  CMakeCache.txt  CMakeFiles  cmake_install.cmake  CMakeLists.txt  COPYING  ENSEMBLES  Makefile  README.md  src  TODO.md  wavefinder-driver

nick:$ make
[  5%] Building C object CMakeFiles/dab2eti.dir/dab.c.o
[ 11%] Building C object CMakeFiles/dab2eti.dir/dab_tables.c.o
[ 17%] Building C object CMakeFiles/dab2eti.dir/depuncture.c.o
[ 23%] Building C object CMakeFiles/dab2eti.dir/fic.c.o
[ 29%] Building C object CMakeFiles/dab2eti.dir/input_sdr.c.o
[ 35%] Building C object CMakeFiles/dab2eti.dir/input_wf.c.o
[ 41%] Building C object CMakeFiles/dab2eti.dir/misc.c.o
[ 47%] Building C object CMakeFiles/dab2eti.dir/sdr_fifo.c.o
[ 52%] Building C object CMakeFiles/dab2eti.dir/sdr_sync.c.o
[ 58%] Building C object CMakeFiles/dab2eti.dir/wf_maths.c.o
[ 64%] Building C object CMakeFiles/dab2eti.dir/wf_prstables.c.o
[ 70%] Building C object CMakeFiles/dab2eti.dir/wf_sync.c.o
[ 76%] Building C object CMakeFiles/dab2eti.dir/dab2eti.c.o
/home/nick/dabtools/dabtools/src/dab2eti.c: In function ‘do_wf_decode’:
/home/nick/dabtools/dabtools/src/dab2eti.c:272:1: warning: no return statement in function returning non-void [-Wreturn-type]
  272 | }
      | ^
/home/nick/dabtools/dabtools/src/dab2eti.c: In function ‘eti_callback’:
/home/nick/dabtools/dabtools/src/dab2eti.c:134:3: warning: ignoring return value of ‘write’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  134 |   write(1, eti, 6144);
      |   ^~~~~~~~~~~~~~~~~~~
[ 82%] Building C object CMakeFiles/dab2eti.dir/viterbi.c.o
[ 88%] Linking C executable dab2eti
[ 88%] Built target dab2eti
[ 94%] Building C object CMakeFiles/eti2mpa.dir/eti2mpa.c.o
/home/nick/dabtools/dabtools/src/eti2mpa.c: In function ‘main’:
/home/nick/dabtools/dabtools/src/eti2mpa.c:72:5: warning: ignoring return value of ‘write’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   72 |     write(1,buf + 12 + 4*NST + FICF*96 + data_offset, data_length);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[100%] Linking C executable eti2mpa
[100%] Built target eti2mpa

nick$  cd ./wavefinder-driver
nick$ ls
60-wavefinder.rules  clean  Makefile  wavefinder.c  wavefinder.fw  wavefinder.h  wfsl11r.h

nick$ make
make -C /lib/modules/6.11.0-17-generic/build M=./dabtools/wavefinder-driver modules
make[1]: Entering directory '/usr/src/linux-headers-6.11.0-17-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  You are using:           gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  CC [M]  /home/nick/Software/dabtools/dabtools/wavefinder-driver/wavefinder.o
  MODPOST /home/nick/Software/dabtools/dabtools/wavefinder-driver/Module.symvers
  CC [M]  /home/nick/Software/dabtools/dabtools/wavefinder-driver/wavefinder.mod.o
  LD [M]  /home/nickSoftware/dabtools/dabtools/wavefinder-driver/wavefinder.ko
  BTF [M] /home/nick/Software/dabtools/dabtools/wavefinder-driver/wavefinder.ko
Skipping BTF generation for /home/nick/Software/dabtools/dabtools/wavefinder-driver/wavefinder.ko due to unavailability of vmlinux
make[1]: Leaving directory '/usr/src/linux-headers-6.11.0-17-generic'
```

**Comment by PartialVolume** [comment]
After I manually install wavefinder.ko using insmod and monitoring dmesg when I plug in the wavefinder I get
```
[10599.623018] usb 3-1: new full-speed USB device number 20 using xhci_hcd
[10599.750307] usb 3-1: New USB device found, idVendor=09cd, idProduct=2001, bcdDevice= 1.01
[10599.750320] usb 3-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[10599.754427] wavefinder: probe: vendor id 0x9cd, device id 0x2001 ifnum:0 intf->minor:1 s=00000000e461de40 wavefinder_t=184
[10599.755332] bound to interface: 0
[10599.755340] wavefinder: probe: intf->minor:1

```

But I still get no devices found
```
./dab2eti 218640000 > dump.eti
No supported devices found.
```

**Comment by PartialVolume** [comment]
Interestingly looking at the readme that says it expects the wavefinder to be /dev/wavefinder0 however mine is located at
```
crw------- 1 root root 180, 1 Mar 15 22:42 /dev/wavefinder1
```

```
## Hardware support

Note that there is currently no way to specify the device - dab2eti
will first look for and use a /dev/wavefinder0 device, and if that is
not found, it will search for RTL-SDR devices.
```

**Comment by LichP** [comment]
Hi @PartialVolume , good to hear from you! While I haven't made any progress on the Linux code since September, I have had some success running the Wavefinder with its original software on an actual Win2k box (hooray for ancient hardware!), which confirmed the device itself works OK. More usefully, I've managed to install Win2k in a QEMU/KVM virtual machine and have run the device from inside that using USB passthrough. This has allowed me to capture some logging with usbmon so I can now see what's going on on the bus during a successful initialisation, tune, and stream. Hopefully this will help in figuring out what's not working on the Linux driver.

Regarding the `/dev/wavefinder1` vs `/dev/wavefinder0` thing, you can always bodge `dab2eti`, it just hard codes the device name, so changing it in `dab2eti.c` on line 293 and recompiling should allow you to experiment.

**Comment by LichP** [comment]
After much USB monitoring and kernel oops funtimes, I've now got a successfully working Wavefinder! The driver now works well enough that the Wavefinder will generally tune within a few attempts, and I've solved some buffering issues that were causing system lockups after a while. I've also cleaned up the driver debug output so there's a lot less spam in dmesg, most of these lines are just commented out so can be brought back easily enough.

It's also worth noting that for playback `madplay` seems to be obsolete these days, however `mpv works quite nicely. For example, to tune in to the BBC national multiplex, select the channel for BBC 6 Music, and play:

```sh
./dab2eti 225648000 | ./eti2mpa 11 | mpv -
```

The wavefinder should light up green and attempt to tune. It might get stuck on the first few attempts at `Waiting for sync...`. If it doesn't change to `Waiting for sync...LOCKED` within about 5-10 seconds, then abort the command and try it again, it usually gets there within about 2-4 tries. Sometimes the Wavefinder will get in a huff though: if the LED doesn't light up green, then unplug it from the USB and power and replug it.

**Comment by PartialVolume** [comment]
Nice one, thanks for the update. I'm in the middle of a house move at the moment, but as soon as the dust settles I'll see if I can get mine working too.
